#!/usr/bin/env bash
set -e

# Build the site with production config.

./tasks/jekyll "_config_production.yml"

# Deploy Message.

if [ $1 ]; then
  message=$1
else
  echo "Fetching last commit message for deploy message..."
  message=$(git log -1 --pretty=%B)
fi
echo "Using commit message:"
echo "$message"

# Preparing deploy repo.

if [ ! -d ../metaskills.github.com ]; then
  echo "No metaskills.github.com deploy repository found! Will clone adjacent to this directory..."
  pushd ..
  git clone git@github.com:metaskills/metaskills.github.com.git
  cd ./metaskills.github.com
else
  echo "Changing to ../metaskills.github.com directory..."
  pushd ../metaskills.github.com
fi

git checkout master
git pull
git branch -D stage
git checkout -b stage

popd

# Sync to deploy repo.

rsync -az --delete --exclude '.git' _site/ ../metaskills.github.com

# Deploy from deploy repo.

pushd ../metaskills.github.com
git add . 

git commit -a -m "$message"
git checkout master
git merge stage
git push -u origin master
git checkout stage

popd

# Rebuild the development site.

./tasks/jekyll
