#!/usr/bin/env bash
set -e

# Create the site and tidy it.

env RM_STAR_SILENT=true rm -rf _site/*

sass --scss --style compressed _sass/site.scss:resource/site.css

jekyll build $*

find _site -name "*.html" -exec tidy -config $(pwd)/tidy.conf {} \;
